name: "Release AssemblyScript SDK"
on:
  push:
    tags:
      - "sdk/assemblyscript/v*"
permissions:
  contents: "write"
jobs:
  release:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - name: "Validate version"
        if: ${{ !startsWith(github.ref_name, 'sdk/assemblyscript/v') }}
        run: 'echo "Modus AssemblyScript SDK version must start with `sdk/assemblyscript/v` && exit 1'
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.ref_name }}"
      - name: Get SDK Version
        id: get_sdk_version
        run: echo "sdk_version=$(echo '${{ github.ref_name }}' | cut -d'/' -f 3)" >> $GITHUB_OUTPUT
      - name: Prepare Templates
        working-directory: sdk/assemblyscript
        run: ./scripts/prepare-templates.sh ${{ steps.get_sdk_version.outputs.sdk_version }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: templates_assemblyscript_${{ steps.get_sdk_version.outputs.sdk_version }}.tar.gz
          prerelease: ${{ contains(steps.get_sdk_version.outputs.sdk_version, '-') }}
          make_latest: false
